/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TtftRouteImport } from './routes/ttft'
import { Route as TrendsRouteImport } from './routes/trends'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as ModelsRouteImport } from './routes/models'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as LatencyRouteImport } from './routes/latency'
import { Route as HeatmapRouteImport } from './routes/heatmap'
import { Route as FinishRouteImport } from './routes/finish'
import { Route as CallsRouteImport } from './routes/calls'
import { Route as CacheRouteImport } from './routes/cache'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TracesIndexRouteImport } from './routes/traces.index'
import { Route as SessionsIndexRouteImport } from './routes/sessions.index'
import { Route as TracesTraceIdRouteImport } from './routes/traces.$traceId'
import { Route as SessionsIdRouteImport } from './routes/sessions.$id'
import { Route as ApiHealthzRouteImport } from './routes/api.healthz'

const TtftRoute = TtftRouteImport.update({
  id: '/ttft',
  path: '/ttft',
  getParentRoute: () => rootRouteImport,
} as any)
const TrendsRoute = TrendsRouteImport.update({
  id: '/trends',
  path: '/trends',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsRoute = ModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const LatencyRoute = LatencyRouteImport.update({
  id: '/latency',
  path: '/latency',
  getParentRoute: () => rootRouteImport,
} as any)
const HeatmapRoute = HeatmapRouteImport.update({
  id: '/heatmap',
  path: '/heatmap',
  getParentRoute: () => rootRouteImport,
} as any)
const FinishRoute = FinishRouteImport.update({
  id: '/finish',
  path: '/finish',
  getParentRoute: () => rootRouteImport,
} as any)
const CallsRoute = CallsRouteImport.update({
  id: '/calls',
  path: '/calls',
  getParentRoute: () => rootRouteImport,
} as any)
const CacheRoute = CacheRouteImport.update({
  id: '/cache',
  path: '/cache',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TracesIndexRoute = TracesIndexRouteImport.update({
  id: '/traces/',
  path: '/traces/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsIndexRoute = SessionsIndexRouteImport.update({
  id: '/sessions/',
  path: '/sessions/',
  getParentRoute: () => rootRouteImport,
} as any)
const TracesTraceIdRoute = TracesTraceIdRouteImport.update({
  id: '/traces/$traceId',
  path: '/traces/$traceId',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsIdRoute = SessionsIdRouteImport.update({
  id: '/sessions/$id',
  path: '/sessions/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthzRoute = ApiHealthzRouteImport.update({
  id: '/api/healthz',
  path: '/api/healthz',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/cache': typeof CacheRoute
  '/calls': typeof CallsRoute
  '/finish': typeof FinishRoute
  '/heatmap': typeof HeatmapRoute
  '/latency': typeof LatencyRoute
  '/logs': typeof LogsRoute
  '/models': typeof ModelsRoute
  '/tools': typeof ToolsRoute
  '/trends': typeof TrendsRoute
  '/ttft': typeof TtftRoute
  '/api/healthz': typeof ApiHealthzRoute
  '/sessions/$id': typeof SessionsIdRoute
  '/traces/$traceId': typeof TracesTraceIdRoute
  '/sessions/': typeof SessionsIndexRoute
  '/traces/': typeof TracesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/cache': typeof CacheRoute
  '/calls': typeof CallsRoute
  '/finish': typeof FinishRoute
  '/heatmap': typeof HeatmapRoute
  '/latency': typeof LatencyRoute
  '/logs': typeof LogsRoute
  '/models': typeof ModelsRoute
  '/tools': typeof ToolsRoute
  '/trends': typeof TrendsRoute
  '/ttft': typeof TtftRoute
  '/api/healthz': typeof ApiHealthzRoute
  '/sessions/$id': typeof SessionsIdRoute
  '/traces/$traceId': typeof TracesTraceIdRoute
  '/sessions': typeof SessionsIndexRoute
  '/traces': typeof TracesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/cache': typeof CacheRoute
  '/calls': typeof CallsRoute
  '/finish': typeof FinishRoute
  '/heatmap': typeof HeatmapRoute
  '/latency': typeof LatencyRoute
  '/logs': typeof LogsRoute
  '/models': typeof ModelsRoute
  '/tools': typeof ToolsRoute
  '/trends': typeof TrendsRoute
  '/ttft': typeof TtftRoute
  '/api/healthz': typeof ApiHealthzRoute
  '/sessions/$id': typeof SessionsIdRoute
  '/traces/$traceId': typeof TracesTraceIdRoute
  '/sessions/': typeof SessionsIndexRoute
  '/traces/': typeof TracesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agents'
    | '/cache'
    | '/calls'
    | '/finish'
    | '/heatmap'
    | '/latency'
    | '/logs'
    | '/models'
    | '/tools'
    | '/trends'
    | '/ttft'
    | '/api/healthz'
    | '/sessions/$id'
    | '/traces/$traceId'
    | '/sessions/'
    | '/traces/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agents'
    | '/cache'
    | '/calls'
    | '/finish'
    | '/heatmap'
    | '/latency'
    | '/logs'
    | '/models'
    | '/tools'
    | '/trends'
    | '/ttft'
    | '/api/healthz'
    | '/sessions/$id'
    | '/traces/$traceId'
    | '/sessions'
    | '/traces'
  id:
    | '__root__'
    | '/'
    | '/agents'
    | '/cache'
    | '/calls'
    | '/finish'
    | '/heatmap'
    | '/latency'
    | '/logs'
    | '/models'
    | '/tools'
    | '/trends'
    | '/ttft'
    | '/api/healthz'
    | '/sessions/$id'
    | '/traces/$traceId'
    | '/sessions/'
    | '/traces/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentsRoute: typeof AgentsRoute
  CacheRoute: typeof CacheRoute
  CallsRoute: typeof CallsRoute
  FinishRoute: typeof FinishRoute
  HeatmapRoute: typeof HeatmapRoute
  LatencyRoute: typeof LatencyRoute
  LogsRoute: typeof LogsRoute
  ModelsRoute: typeof ModelsRoute
  ToolsRoute: typeof ToolsRoute
  TrendsRoute: typeof TrendsRoute
  TtftRoute: typeof TtftRoute
  ApiHealthzRoute: typeof ApiHealthzRoute
  SessionsIdRoute: typeof SessionsIdRoute
  TracesTraceIdRoute: typeof TracesTraceIdRoute
  SessionsIndexRoute: typeof SessionsIndexRoute
  TracesIndexRoute: typeof TracesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ttft': {
      id: '/ttft'
      path: '/ttft'
      fullPath: '/ttft'
      preLoaderRoute: typeof TtftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trends': {
      id: '/trends'
      path: '/trends'
      fullPath: '/trends'
      preLoaderRoute: typeof TrendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models': {
      id: '/models'
      path: '/models'
      fullPath: '/models'
      preLoaderRoute: typeof ModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/latency': {
      id: '/latency'
      path: '/latency'
      fullPath: '/latency'
      preLoaderRoute: typeof LatencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/heatmap': {
      id: '/heatmap'
      path: '/heatmap'
      fullPath: '/heatmap'
      preLoaderRoute: typeof HeatmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finish': {
      id: '/finish'
      path: '/finish'
      fullPath: '/finish'
      preLoaderRoute: typeof FinishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calls': {
      id: '/calls'
      path: '/calls'
      fullPath: '/calls'
      preLoaderRoute: typeof CallsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cache': {
      id: '/cache'
      path: '/cache'
      fullPath: '/cache'
      preLoaderRoute: typeof CacheRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/traces/': {
      id: '/traces/'
      path: '/traces'
      fullPath: '/traces/'
      preLoaderRoute: typeof TracesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/': {
      id: '/sessions/'
      path: '/sessions'
      fullPath: '/sessions/'
      preLoaderRoute: typeof SessionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/traces/$traceId': {
      id: '/traces/$traceId'
      path: '/traces/$traceId'
      fullPath: '/traces/$traceId'
      preLoaderRoute: typeof TracesTraceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/$id': {
      id: '/sessions/$id'
      path: '/sessions/$id'
      fullPath: '/sessions/$id'
      preLoaderRoute: typeof SessionsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/healthz': {
      id: '/api/healthz'
      path: '/api/healthz'
      fullPath: '/api/healthz'
      preLoaderRoute: typeof ApiHealthzRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentsRoute: AgentsRoute,
  CacheRoute: CacheRoute,
  CallsRoute: CallsRoute,
  FinishRoute: FinishRoute,
  HeatmapRoute: HeatmapRoute,
  LatencyRoute: LatencyRoute,
  LogsRoute: LogsRoute,
  ModelsRoute: ModelsRoute,
  ToolsRoute: ToolsRoute,
  TrendsRoute: TrendsRoute,
  TtftRoute: TtftRoute,
  ApiHealthzRoute: ApiHealthzRoute,
  SessionsIdRoute: SessionsIdRoute,
  TracesTraceIdRoute: TracesTraceIdRoute,
  SessionsIndexRoute: SessionsIndexRoute,
  TracesIndexRoute: TracesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
