---
version: 2
updates:
  - package-ecosystem: npm
    directory: /apps/dashboard
    schedule:
      interval: daily
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - javascript

  - package-ecosystem: docker
    directory: /apps/dashboard
    schedule:
      interval: daily
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - docker

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - github-actions
